import { NextResponse } from 'next/server'
import { z } from 'zod'
import { prisma } from '@/lib/db'
import { clientIp, rateLimit } from '@/lib/rate-limit'
import { isBot, classifySource, referrerHost, pruneOldVisits } from '@/lib/analytics'
import { appUrl } from '@/lib/site'

/**
 * Records a visit for the shop's own admin dashboard.
 *
 * Unauthenticated by necessity — it counts visitors, and visitors are not
 * signed in. Four things keep that from being a liability:
 *
 *  1. **It stores almost nothing.** A random per-tab id, how they arrived, a
 *     referring host and two timestamps. No page path, no IP, no user agent,
 *     no cookie, no link to any customer or order. There is nothing here worth
 *     stealing and nothing that identifies a person.
 *  2. **It is rate limited per IP**, so it cannot be used to inflate the
 *     numbers or to fill the table.
 *  3. **Input is refused, not repaired.** An id that is not the expected shape
 *     is dropped rather than cleaned into something plausible.
 *  4. **It always answers 204.** Failures are silent by design — a visitor
 *     should never see an error, and a caller should learn nothing from the
 *     response about whether anything was written.
 */

const schema = z.object({
  visitId: z
    .string()
    // Generated by the client as a UUID; accept that shape and nothing longer.
    .regex(/^[A-Za-z0-9-]{8,64}$/),
})

/** 204 with no body. Every path out of this route returns exactly this. */
const noContent = () => new NextResponse(null, { status: 204 })

/**
 * Roughly one request in fifty also prunes. Cheap on average, self-maintaining,
 * and no cron to forget about. A failure here must not affect the visitor, so
 * it is swallowed.
 */
async function maybePrune() {
  if (Math.random() >= 0.02) return
  try {
    await pruneOldVisits()
  } catch {
    // Retention is best-effort; the next request will try again.
  }
}

export async function POST(request: Request) {
  // Bots first: no reason to spend a rate-limit slot or a database write.
  if (isBot(request.headers.get('user-agent'))) return noContent()

  const limit = await rateLimit(`track:${clientIp(request)}`, {
    limit: 120,
    windowMs: 5 * 60 * 1000,
  })
  if (!limit.ok) return noContent()

  const parsed = schema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) return noContent()

  let selfHost: string | null = null
  try {
    selfHost = new URL(appUrl()).hostname
  } catch {
    selfHost = null
  }

  const host = referrerHost(request.headers.get('referer'), selfHost)

  try {
    /**
     * One row per visit, however many pages it becomes.
     *
     * The update deliberately touches only `lastSeenAt`. After the first page
     * the referrer is our own site, which `referrerHost` correctly reduces to
     * null — so writing `source` on every report would relabel every visit
     * that lasted more than one page as "direct", and search and link traffic
     * would silently disappear from the numbers.
     */
    await prisma.visit.upsert({
      where: { id: parsed.data.visitId },
      create: {
        id: parsed.data.visitId,
        source: classifySource(host),
        referrerHost: host,
      },
      update: { lastSeenAt: new Date() },
    })
  } catch {
    // A missed visit is not worth an error page. Swallow and move on.
  }

  await maybePrune()
  return noContent()
}
