import { NextResponse } from 'next/server'
import { z } from 'zod'
import { prisma } from '@/lib/db'
import { clientIp, rateLimit } from '@/lib/rate-limit'
import { isBot, normalisePath, referrerHost, pruneOldViews } from '@/lib/analytics'
import { appUrl } from '@/lib/site'

/**
 * Records one page view for the shop's own admin dashboard.
 *
 * Unauthenticated by necessity — it counts visitors, and visitors are not
 * signed in. Four things keep that from being a liability:
 *
 *  1. **It stores almost nothing.** A path, a per-tab random id, a referring
 *     host and a timestamp. No IP, no user agent, no cookie, no link to any
 *     customer or order. There is nothing here worth stealing and nothing that
 *     identifies a person.
 *  2. **It is rate limited per IP**, so it cannot be used to inflate the
 *     numbers or to fill the table.
 *  3. **Input is refused, not repaired.** A path that is not a plain absolute
 *     path is dropped rather than cleaned into something plausible.
 *  4. **It always answers 204.** Failures are silent by design — a visitor
 *     should never see an error, and a caller should learn nothing from the
 *     response about whether anything was written.
 */

const schema = z.object({
  path: z.string().max(600),
  sessionId: z
    .string()
    // Generated by the client as a UUID; accept that shape and nothing longer.
    .regex(/^[A-Za-z0-9-]{8,64}$/),
  /** A keep-alive from a tab that is still open, rather than a page load. */
  ping: z.boolean().optional().default(false),
})

/** 204 with no body. Every path out of this route returns exactly this. */
const noContent = () => new NextResponse(null, { status: 204 })

/**
 * Roughly one request in fifty also prunes. Cheap on average, self-maintaining,
 * and no cron to forget about. A failure here must not affect the visitor, so
 * it is swallowed.
 */
async function maybePrune() {
  if (Math.random() >= 0.02) return
  try {
    await pruneOldViews()
  } catch {
    // Retention is best-effort; the next request will try again.
  }
}

export async function POST(request: Request) {
  // Bots first: no reason to spend a rate-limit slot or a database write.
  if (isBot(request.headers.get('user-agent'))) return noContent()

  const limit = await rateLimit(`track:${clientIp(request)}`, {
    limit: 120,
    windowMs: 5 * 60 * 1000,
  })
  if (!limit.ok) return noContent()

  const parsed = schema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) return noContent()

  const path = normalisePath(parsed.data.path)
  if (!path) return noContent()

  let selfHost: string | null = null
  try {
    selfHost = new URL(appUrl()).hostname
  } catch {
    selfHost = null
  }

  try {
    await prisma.pageView.create({
      data: {
        path,
        sessionId: parsed.data.sessionId,
        referrerHost: referrerHost(request.headers.get('referer'), selfHost),
      },
    })
  } catch {
    // A missed view is not worth an error page. Swallow and move on.
  }

  await maybePrune()
  return noContent()
}
